version: '3.2'



services:
    selenium:
        image: selenium/standalone-chrome:latest
        ports:
          -4444:4444
        restart: always

    app:
      build:
        context:
      volumes:
        - .app/:/app
      command: sh-c "python3 sample.py"
      depends_on:
        -selenium

